### ISSUE TITLE
Support for servers that return '0' for total page count in an empty result?

### ISSUE THREAD

**Issue by mbhnyc** [backbone-paginator/backbone-pageable#53]
Hey guys,

Probably a pretty easy one here, but my API stack (https://github.com/filtersquad/rocket_pants) with Kaminari (https://github.com/amatsuda/kaminari) returns results like the following:

```
{"response":[],"count":0,"pagination":{"current":1,"previous":null,"next":2,"per_page":30,"pages":0,"count":0}}
```

Most of which I've been able to translate very effectively in the settings block:

```
queryParams:
   currentPage: "page"
   pageSize: 10
   totalPages: "pages"
   totalRecords: "count"
```

Sadly Pageable gets upset that my total pages count is also zero-based (line 574).  Is there a configuration fix here that I'm missing, or do we need do a PR?  I hacked at it for a few minutes, but wasn't sure that bypassing the exception at like 574 would break the library elsewhere.
